templates = {
    "Reservations": [
        "Almost full! 🚨 Only 4 tables left for tonight’s dinner service. Don't get stuck waiting at the door. Book now: {link}",
        "Don’t feel like cooking? 🍝 We’ve got the stove on. Skip the dishes and enjoy a relaxing meal with us. Reserve here: {link}",
        "Priority Seating: We opened up 5 extra slots for our VIP list tonight. Claim yours before the public does. {link}",
        "The weekend rush is coming! 🏃‍♂️ Secure your Friday night table now so you aren't left hungry later. Book: {link}",
        "Everyone is talking about our new patio. Come see why it’s the hottest spot in town. Reserve a table: {link}",
        "Date night made easy. 🍷 Candlelight, wine, and zero stress. We have a table with your name on it. Book: {link}",
        "Hungry? We're ready for you. Secure your spot now and walk right in when you arrive. Reserve: {link}",
        "Tonight's special is incredible... but it requires a reservation. Don't miss out on the chef's surprise. {link}",
        "Last call for dinner reservations! 🕒 Book by 4pm to guarantee your seating preference. {link}",
        "Pizza + Beer + You? 🍕 Sounds like a plan. Grab a booth before the game starts. Reserve: {link}",
        "Tonight’s lineup is filling fast! ⚡ Grab a table before we hit capacity: {link}",
        "Your seat is waiting… for now. 👀 Lock in dinner plans while openings remain: {link}",
        "Craving something good? 🍽️ We’ve got space at 7pm with your name on it. Book here: {link}",
        "Skip the waitlist tonight. 🙌 Reserve ahead and walk right in: {link}",
        "The kitchen is fired up. 🔥 Claim a table and let us cook for you: {link}",
        "Early birds win dinner. 🕔 Book now for the best time slots tonight: {link}",
        "Your perfect night out starts with a reservation. ✨ Grab a table: {link}",
        "Planning dinner last minute? We opened a few extra tables. Snag one: {link}",
        "Treat yourself tonight. 🍷 A calm meal is one reservation away: {link}",
        "Want first dibs on tonight’s specials? Reserve to guarantee your pick: {link}",
    ],
    "Featured Dish": [
        "Sizzling, savory, and perfect. 🥩 Our {item} is grilled to perfection tonight. Taste the difference. Order now: {link}",
        "Selling fast! 📉 Our {item} is flying out of the kitchen. Get it before we run out. Order: {link}",
        "Craving comfort? Our {item} is back. It’s the hug you can eat. Reserve yours: {link}",
        # "The Chef just prepped a secret off-menu dish. 🤫 Ask for the "Midnight Burger" or order online here: {link}",
        "Fresh catch alert! 🐟 We just got a shipment of wild salmon. It doesn't get fresher than this. Taste it: {link}",
        "You have great taste. That’s why you need to try our award-winning {item}. See why it won Gold. {link}",
        "Only 20 orders available. Our {item} takes 12 hours to make, and it goes fast. Claim one: {link}",
        "Best paired with red wine: {item}. 🍷 Make your dinner effortless tonight. View menu: {link}",
        "Tonight’s Star: {item}.  Indulge in a little luxury this Tuesday. Reserve: {link}",
        "Tonight’s hero: {item}. Juicy + crispy = perfect. Order: {link}",
        "The chef is plating something wild: Smoked Gouda Mash. 🤤 Try it while it lasts: {link}",
        "Comfort in a bowl: {item}. Perfect for chilly nights: {link}",
        "Flavor bomb alert {item} is back and better. Order now: {link}",
        "If cozy had a taste, it’d be our {item}. 🥧 Reserve yours: {link}",
        "Meet your new favorite: {item}. 😍 Limited servings: {link}",
        "Our House Burger just leveled up with a brioche bun. 🍔 Come test the upgrade: {link}",
        "Tonight’s indulgence: {item}. 🍟 Fancy without the fuss. Try them: {link}",
    ],
    "Featured Drink": [
        "Long day? You need a margarita. 🍹 Salt rim, fresh lime, zero worries. Come sip with us: {link}",
        "New Tap Alert! 🍺 We just kegged a local hazy IPA. It’s crisp, cold, and waiting for you. See tap list: {link}",
        "Drinks taste better with friends. 🥂 Tag a buddy and come share a pitcher of Sangria tonight. Book: {link}",
        "Craft Cocktail Night. 🍸 Our mixologists are showing off tonight. Come taste their latest creation. {link}",
        "Small Batch Bourbon just arrived. 🥃 We have limited pours of this rare bottle. Reserve a glass: {link}",
        "Patio weather = Rose weather. ☀️ Come cool off with a glass of pink. Tables open now: {link}",
        "Thirsty Thursday! All specialty martinis are $2 off. 🍸 High class, low price. See the list: {link}",
        "Need a boost? Our Espresso Martini is the wake-up call you actually want. ☕🍸 Come try it: {link}",
        "It’s getting cold outside. Warm up with our Spiked Apple Cider. 🍎 Cozy vibes inside. {link}",
        "Think you can handle the heat? 🌶️ Try our Jalapeno Margarita. Spicy, sour, delicious. {link}",
        "Frosty Paloma waiting for you. 🍊 Light, crisp, refreshing. Come sip: {link}",
        "New cocktail drop: Blackberry Smash. 🍇 Sweet, tart, delicious. Try it: {link}",
        "Cold beer, warm patio. 🍺☀️ Perfect combo. Grab a table: {link}",
        "Whiskey fans — our Old Fashioned got a glow-up. 🥃 Taste the upgrade: {link}",
        "Meet your new summer crush: Frozen Peach Bellini. 🍑 Cool off here: {link}",
        "Local cider tapped today! 🍏 Fresh, crisp, lightly sweet. Pouring now: {link}",
        "Sangria Sunday? 🍷 Fruits soaking. Pitchers flowing. Join us: {link}",
        "Feeling fancy? ✨ Our Lavender Lemon Martini is the moment. {link}",
        "Cold brew + vodka = magic. ☕✨ Try the Cold Brew Cocktail tonight: {link}",
        "Fresh mint + lime = perfect Mojito. 🍃 Beat the heat with one: {link}",
    ],
    "Dessert Special": [
        "Save room! 🍰 Our Molten Lava Cake is worth the calories. Treat yourself tonight. Reserve: {link}",
        "Limited Batch: We made 12 Tiramisus today. Once they're gone, they're gone. Claim yours: {link}",
        "Date night? Split the Grand Sundae. 🍨 Two spoons, one delicious bowl. Book a table: {link}",
        "Warm cookies + Cold milk. 🍪 Sometimes simple is best. Come get a fresh batch. {link}",
        # Not on the menu: Ask for the "Berry Bliss" tonight for a secret sweet treat. 🍓 Reserve: {link},
        "Sweet tooth aching? We have the cure. New Cheesecake flavor just dropped. See it here: {link}",
        "Gluten-Free Chocolate Cake? Yes, it exists and it’s amazing. 🍫 Eat without worry. {link}",
        "Life is short. Eat dessert first. 🎂 Our Red Velvet cake is waiting. Order takeout: {link}",
        "Fluffy, creamy, dreamy. Our key lime pie is the perfect end to your meal. 🍋 Grab a slice: {link}",
        "The Pumpkin Cheesecake leaves the menu Sunday! 🎃 Get your last slice before next year. {link}",
    ],
}
