templates = {
    "Reservations": [
        "Almost full! Only 4 tables left for tonight’s dinner service. Don't get stuck waiting at the door. Book now: {link}",
        "Don’t feel like cooking? We’ve got the stove on. Skip the dishes and enjoy a relaxing meal with us. Reserve here: {link}",
        "Priority Seating: We opened up 5 extra slots for our VIP list tonight. Claim yours before the public does. {link}",
        "The weekend rush is coming! Secure your Friday night table now so you aren't left hungry later. Book: {link}",
        "Everyone is talking about our new patio. Come see why it’s the hottest spot in town. Reserve a table: {link}",
        "Date night made easy. Candlelight, wine, and zero stress. We have a table with your name on it. Book: {link}",
        "Hungry? We're ready for you. Secure your spot now and walk right in when you arrive. Reserve: {link}",
        "Tonight's special is incredible... but it requires a reservation. Don't miss out on the chef's surprise. {link}",
        "Last call for dinner reservations! Book by 4pm to guarantee your seating preference. {link}",
        "Pizza + Beer + You? Sounds like a plan. Grab a booth before the game starts. Reserve: {link}",
        "Tonight’s lineup is filling fast! Grab a table before we hit capacity: {link}",
        "Your seat is waiting… for now. Lock in dinner plans while openings remain: {link}",
        "Craving something good? We’ve got space at 7pm with your name on it. Book here: {link}",
        "Skip the waitlist tonight. Reserve ahead and walk right in: {link}",
        "The kitchen is fired up. Claim a table and let us cook for you: {link}",
        "Early birds win dinner. Book now for the best time slots tonight: {link}",
        "Your perfect night out starts with a reservation. Grab a table: {link}",
        "Planning dinner last minute? We opened a few extra tables. Snag one: {link}",
        "Treat yourself tonight. A calm meal is one reservation away: {link}",
        "Want first dibs on tonight’s specials? Reserve to guarantee your pick: {link}",
    ],
    "Featured Dish": [
        "Sizzling, savory, and perfect. Our {item} is grilled to perfection tonight. Taste the difference. Order now: {link}",
        "Selling fast! Our {item} is flying out of the kitchen. Get it before we run out. Order: {link}",
        "Craving comfort? Our {item} is back. It’s the hug you can eat. Reserve yours: {link}",
        # "The Chef just prepped a secret off-menu dish. 🤫 Ask for the "Midnight Burger" or order online here: {link}",
        "Fresh catch alert! We just got a shipment of wild salmon. It doesn't get fresher than this. Taste it: {link}",
        "You have great taste. That’s why you need to try our award-winning {item}. See why it won Gold. {link}",
        "Only 20 orders available. Our {item} takes 12 hours to make, and it goes fast. Claim one: {link}",
        "Best paired with red wine: {item}. Make your dinner effortless tonight. View menu: {link}",
        "Tonight’s Star: {item}. Indulge in a little luxury this Tuesday. Reserve: {link}",
        "Tonight’s hero: {item}. Juicy + crispy = perfect. Order: {link}",
        "The chef is plating something wild: {item}. Try it while it lasts: {link}",
        "Comfort in a bowl: {item}. Perfect for chilly nights: {link}",
        "Flavor bomb alert {item} is back and better. Order now: {link}",
        "If cozy had a taste, it’d be our {item}. Reserve yours: {link}",
        "Meet your new favorite: {item}. Limited servings: {link}",
        "Our House Burger just leveled up with a brioche bun. Come test the upgrade: {link}",
        "Tonight’s indulgence: {item}. Fancy without the fuss. Try them: {link}",
    ],
    "Featured Drink": [
        "Long day? You need a margarita. Salt rim, fresh lime, zero worries. Come sip with us: {link}",
        "New Tap Alert! We just kegged a local hazy IPA. It’s crisp, cold, and waiting for you. See tap list: {link}",
        "Drinks taste better with friends. Tag a buddy and come share a pitcher of Sangria tonight. Book: {link}",
        "Craft Cocktail Night. Our mixologists are showing off tonight. Come taste their latest creation. {link}",
        "Small Batch Bourbon just arrived. We have limited pours of this rare bottle. Reserve a glass: {link}",
        "Patio weather = Rose weather. Come cool off with a glass of pink. Tables open now: {link}",
        "Thirsty Thursday! All specialty martinis are $2 off. High class, low price. See the list: {link}",
        "Need a boost? Our Espresso Martini is the wake-up call you actually want. Come try it: {link}",
        "It’s getting cold outside. Warm up with our Spiked Apple Cider. Cozy vibes inside. {link}",
        "Think you can handle the heat? Try our Jalapeno Margarita. Spicy, sour, delicious. {link}",
        "Frosty Paloma waiting for you. Light, crisp, refreshing. Come sip: {link}",
        "New cocktail drop: Blackberry Smash. Sweet, tart, delicious. Try it: {link}",
        "Cold beer, warm patio. Perfect combo. Grab a table: {link}",
        "Whiskey fans — our Old Fashioned got a glow-up. Taste the upgrade: {link}",
        "Meet your new summer crush: Frozen Peach Bellini. Cool off here: {link}",
        "Local cider tapped today! Fresh, crisp, lightly sweet. Pouring now: {link}",
        "Sangria Sunday? Fruits soaking. Pitchers flowing. Join us: {link}",
        "Feeling fancy? Our Lavender Lemon Martini is the moment. {link}",
        "Cold brew + vodka = magic. Try the Cold Brew Cocktail tonight: {link}",
        "Fresh mint + lime = perfect Mojito. Beat the heat with one: {link}",
    ],
    "Dessert Special": [
        "Save room! Our Molten Lava Cake is worth the calories. Treat yourself tonight. Reserve: {link}",
        "Limited Batch: We made 12 Tiramisus today. Once they're gone, they're gone. Claim yours: {link}",
        "Date night? Split the Grand Sundae. Two spoons, one delicious bowl. Book a table: {link}",
        "Warm cookies + Cold milk. Sometimes simple is best. Come get a fresh batch. {link}",
        # Not on the menu: Ask for the "Berry Bliss" tonight for a secret sweet treat. Reserve: {link},
        "Sweet tooth aching? We have the cure. New Cheesecake flavor just dropped. See it here: {link}",
        "Gluten-Free Chocolate Cake? Yes, it exists and it’s amazing. Eat without worry. {link}",
        "Life is short. Eat dessert first. Our Red Velvet cake is waiting. Order takeout: {link}",
        "Fluffy, creamy, dreamy. Our key lime pie is the perfect end to your meal. Grab a slice: {link}",
        "The Pumpkin Cheesecake leaves the menu Sunday! Get your last slice before next year. {link}",
    ],
    "Event / Entertainment Night": [
        "Cooking Class with Our Chef Learn to make our signature dishes this Sunday at 3pm. Sign up now: {link}",
        "Live Music Tonight! The band starts at 8pm. Don't hear about it tomorrow, be there tonight. Book: {link}",
        "Trivia Night! Think you’re smart? Win a $50 tab tonight. Teams forming now. Sign up: {link}",
        "DJ spinning tonight. Good beats, strong drinks, late night vibes. Get on the guest list: {link}",
        "Game On! 10 screens, sound ON. Watch the big game with wings and beer. Reserve a seat: {link}",
        "Ready to laugh? Comedy night starts at 9pm. Grab a ticket before we sell out. {link}",
        "Wine Tasting Event. Taste 5 regions in one night. Very limited spots left. Tickets: {link}",
        "Karaoke Alert! Your stage awaits. Liquid courage available at the bar. Sing with us: {link}",
        "Jazz & Dinner. Smooth tunes for a romantic evening. Perfect for date night. Book: {link}",
        "Kids Eat Free + Magic Show! Fun for the whole family this Tuesday. Reserve a booth: {link}",
        "Charity Night. 10% of proceeds go to local shelters. Eat good, do good. Join us: {link}",
    ],
    "Happy Hour": [
        "Clock’s ticking! Happy Hour ends in 2 hours. $5 drafts and 1/2 price apps. Hurry in! {link}",
        "You survived the work day. Reward yourself with a cold one. Happy Hour starts NOW. Menu: {link}",
        "Why pay full price? 4-6pm is the sweet spot. Sliders and Beers for cheap. Come by: {link}",
        "Grab a coworker and get over here. First round is the hardest decision you'll make today. {link}",
        "SMS Only: Show this text for extended Happy Hour prices until 7pm! Cheers. {link}",
        "Dollar Oysters. Fresh shucked and cheap. They go fast during Happy Hour! Reserve: {link}",
        "Beat the traffic. Stop in for a drink instead of sitting in your car. Happy hour is on. {link}",
        "Flight Night. Try 4 beers for the price of 1 during Happy Hour. Find your new fav. {link}",
        "It’s Friday somewhere. Kick off the weekend early with our 3pm Happy Hour. Join us: {link}",
        "$4 Tacos. $5 Margs. Need we say more? See you at 5pm. {link}",
    ],
    "Brunch": [
        "Sunday Funday starts here. Bottomless Mimosas are flowing. Secure your table: {link}",
        "Rough night? Our Hangover Burger will fix you right up. Brunch is served until 3pm. {link}",
        "Pancakes or Waffles? Why not both? The ultimate brunch stack is waiting. Book now: {link}",
        "Brunch tables fill fast! Don't wait in line hungry. Reserve your spot for this Sunday: {link}",
        "Eggs Benny like you’ve never had. Truffle hollandaise is a game changer. Taste it: {link}",
        "Gather the squad. Brunch is better together. We have large booths available. Book: {link}",
        "Patio Brunch is back! Sun, shades, and iced coffee. The perfect Saturday morning. {link}",
        "Boozy Brunch Deal: Entree + Unlimited Mimosas for $35. Best deal in town. Reserve: {link}",
        "Avocado Toast Upgrade. Fresh, local, and delicious. Start your day right. Menu: {link}",
        "Last Call: Brunch ends at 2pm! You have 1 hour to get your French Toast fix. Hurry in: {link}",
    ],
    "Catering Service": [
        "Hosting a party? Don't stress the food. We cater, you take the credit. Get a quote: {link}",
        "Boring lunch meeting? Spice it up with our taco bar catering. Your team will love you. {link}",
        "Holiday slots are filling! Book your event catering now before we are fully booked. {link}",
        "Wedding or Birthday? Make it memorable with our premium catering packages. See menu: {link}",
        "Boxed Lunches to go. Easy, sanitary, and delicious for large groups. Order here: {link}",
        "Big crowd? No problem. We can feed 10 to 200 people. Let’s plan your menu: {link}",
        "Free delivery on first catering orders over $200! Use code CATER20. Order now: {link}",
        "Not just a set menu. We build custom catering menus to fit your budget. Chat with us: {link}",
        "Game Day: Tailgating? Grab our Wing Platter for the big game. Pre-order required. {link}",
        "Be the host with the most. Let us handle the cooking. Inquiry form here: {link}",
    ],
    "Customer Win-Back": [
        "We miss you! Here is a $10 voucher for your next visit. Come say hi this week. Claim: {link}",
        "You haven't seen our new look! We renovated and want you to see it. Free drink on us: {link}",
        "Happy Birthday (belated)! We missed your big day. Come in for a free dessert. {link}",
        "Where did you go? Tell us why you haven't visited and get a 20% off coupon. Survey: {link}",
        "It's been 30 days! Your usual table is waiting. Book now for a complimentary app. {link}",
        "You’re missing out. We launched a new menu since you last visited. Come taste it: {link}",
        "This offer expires in 48 hours. Come back and get BOGO entrees. Don't let it waste. {link}",
        "You used to be a regular. We want our VIP back. Here’s a special perk just for you: {link}",
        "Stranger! Long time no see. Come grab a beer, first one is on the house. {link}",
        "You have unused loyalty points! They expire soon. Come use them up. Check balance: {link}",
    ],
    "New Menu Item": [
        "It’s finally here. The {item} just hit the menu. Be the first to try it. {link}",
        "Spicy. Sweet. Crunchy. Our new {item} hits every note. Order for lunch: {link}",
        "You asked, we listened. The Viral {item} is now available at our spot. Taste it: {link}",
        "Want to judge our food? Try the new {item} and tell us what you think. Reserve: {link}",
        "Spring on a plate. Our new seasonal menu is light, fresh, and green. See it: {link}",
        "Look at this cheese pull. The new {item} is insane. Order yours: {link}",
        "Limited Run: We are testing the {item} for 1 week only. Try it before it leaves. {link}",
        "Bored of the usual? Switch it up with our new {item}. Spice up your life. {link}",
        "We upgraded the recipe. The new & improved {item} is fudgier than ever. Try it: {link}",
        "New Drop Alert. 3 new appetizers just landed. Perfect for sharing. Menu: {link}",
    ],
    "Seasonal / Holiday Special": [
        "Valentine's is approaching! We have a romantic set menu for two. Book before we fill: {link}",
        "Thanksgiving To-Go. We cook the turkey, you watch football. Pre-order your feast: {link}",
        "Spooky Sips! Come try our Halloween cocktails. Scary good. Tonight only. {link}",
        "Mother's Day Brunch. Mom deserves mimosas. treat her right. Tables going fast: {link}",
        "St. Patrick's Day! Green beer and Corned Beef. Come get lucky with us. {link}",
        "Summer Solstice Party. Longest day of the year means longest happy hour! Join us: {link}",
        "Baby it’s cold outside. Warm up with our limited Hot Cocoa bar. Kids love it. {link}",
        "Ring in the New Year! Champagne toast included with every dinner reservation. Book: {link}",
        "Fish Fry Friday! Crispy cod and fries. The tradition continues this week. Order: {link}",
        "Christmas Parties? We have a private room for your office party. Book it now: {link}",
    ],
    "Loyalty / VIP Message": [
        "VIP Alert. As a top tier member, you get first access to our new menu. Book now: {link}",
        "You’ve earned it! You hit 100 points. Here is your $10 reward voucher. Redeem: {link}",
        # "Secret Menu Item. Ask your server for "The Godfather" tonight. Only for loyalty members. {link}",
        "VIP Tasting. We are hosting a free wine tasting for our top 20 guests. RSVP here: {link}",
        "Double Points Day! Earn 2x points on every dollar spent today. Lunch or Dinner. {link}",
        "Happy Birthday VIP! A free entree is loaded on your account. Valid all month. {link}",
        "Skip the line. VIPs get priority booking for Valentine's Day. Link opens now: {link}",
        "Thanks for being a regular. We appreciate you. Enjoy a free dessert on your next visit. {link}",
        "Kitchen Confidential. Chef wants your opinion on a new dish. Come test it for free. {link}",
        "Share the love. Refer a friend and you BOTH get $20. Start earning here: {link}",
    ],
}
